-- Migration: Add saved_designs table for customer design persistence
-- Date: 2026-04-10
-- Purpose: Allow customers to save and resume their customization designs

CREATE TABLE saved_designs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    customer_id UUID REFERENCES customers(id) ON DELETE CASCADE,
    product_id UUID REFERENCES products(id),
    design_name TEXT NOT NULL DEFAULT 'Untitled Design',
    design_data JSONB NOT NULL,
    preview_image_url TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes for performance
CREATE INDEX idx_saved_designs_customer ON saved_designs(customer_id);
CREATE INDEX idx_saved_designs_product ON saved_designs(product_id);
CREATE INDEX idx_saved_designs_created_at ON saved_designs(created_at DESC);

-- Enable Row Level Security
ALTER TABLE saved_designs ENABLE ROW LEVEL SECURITY;

-- RLS Policies
-- Customers can only see and manage their own saved designs
CREATE POLICY "Customers can view their own saved designs" ON saved_designs
    FOR SELECT USING (
        (customer_id = (SELECT id FROM customers WHERE id = auth.uid()))
        OR 
        (customer_id = (SELECT customer_id FROM sessions WHERE session_id = current_setting('app.current_session_id', true)))
    );

CREATE POLICY "Customers can insert their own saved designs" ON saved_designs
    FOR INSERT WITH CHECK (
        (customer_id = (SELECT id FROM customers WHERE id = auth.uid()))
        OR 
        (customer_id = (SELECT customer_id FROM sessions WHERE session_id = current_setting('app.current_session_id', true)))
    );

CREATE POLICY "Customers can update their own saved designs" ON saved_designs
    FOR UPDATE USING (
        (customer_id = (SELECT id FROM customers WHERE id = auth.uid()))
        OR 
        (customer_id = (SELECT customer_id FROM sessions WHERE session_id = current_setting('app.current_session_id', true)))
    );

CREATE POLICY "Customers can delete their own saved designs" ON saved_designs
    FOR DELETE USING (
        (customer_id = (SELECT id FROM customers WHERE id = auth.uid()))
        OR 
        (customer_id = (SELECT customer_id FROM sessions WHERE session_id = current_setting('app.current_session_id', true)))
    );

-- Admin access policy
CREATE POLICY "Admins can manage all saved designs" ON saved_designs
    FOR ALL USING (
        EXISTS (
            SELECT 1 FROM customers 
            WHERE id = auth.uid() 
            AND is_admin = true
        )
    );

-- Trigger to update updated_at timestamp
CREATE OR REPLACE FUNCTION update_saved_designs_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_saved_designs_updated_at
    BEFORE UPDATE ON saved_designs
    FOR EACH ROW
    EXECUTE FUNCTION update_saved_designs_updated_at();

-- Add comments for documentation
COMMENT ON TABLE saved_designs IS 'Customer saved customization designs for reuse and continuation';
COMMENT ON COLUMN saved_designs.design_data IS 'JSONB storage of DesignSpecification object from customization module';
COMMENT ON COLUMN saved_designs.preview_image_url IS 'URL to preview image generated by customization tool';
COMMENT ON COLUMN saved_designs.design_name IS 'Customer-provided name for the design, defaults to "Untitled Design"';